version = 1

exclude_patterns = [
    "docs/**",
    "examples/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/muxinc/mux-go"]
  import_root = "github.com/muxinc/mux-go"
